name: E2E Workflow for Connext

on:
  push:
    branches:
      - main
      - staging
      - prod
  pull_request:
  create:
    tag:
      - "v*"

jobs:
  build-and-test:
    if: github.ref != 'refs/heads/staging'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      DATABASE_URL: postgres://postgres:qwerty@localhost:5432/connext?sslmode=disable

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: qwerty
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2