name: Harbor Testnet

on:
  workflow_run:
    workflows:
      - E2E Workflow for Connext
    types:
      - completed

jobs:
  init:
    name: Initial steps for harbor
    if: github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          # token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.workflow_run.head_sha }}
    
      - name: Get Commit value
        id: commit
        uses: pr-mpt/actions-commit-hash@v2
        with:
          commit: "${{ github.event.workflow_run.head_sha }}"
          prefix: "sha-"
      
      - name: Echo tag name (sha-short)
        run: echo ${{ steps.commit.outputs.short }}

        

      




      
